config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Food Routes
  get 'foods/' => 'foods#index', as: 'foods'
  get 'foods/new' => 'foods#new', as: 'add_food'
  get 'foods/delete/:id' => 'foods#destroy', as: 'delete_food'
  get 'general_shopping_list' => 'foods#shopping_list', as: 'shopping_list'

  post 'foods/create' => 'foods#create', as: 'create_food'

  # User routes
  resources :users

  # Recipe routes
  get 'public_recipes' => 'recipes#public_recipes'
  get 'recipes/:id/add_ingredient' => 'recipe_foods#new', as:'add_recipe_food'
  resources :recipes
  # for updating the public 
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public_recipe'

  get 'recipe_foods' => 'recipe_foods#index', as:'recipe_foods'
  get 'recipe_foods/delete/:id' => 'recipe_foods#destroy', as: 'delete_recipe_food'

  post 'recipe_foods/create' => 'recipe_foods#create', as:'create_recipe_food'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  root "foods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :quantity, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cook_time, presence: true
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :foods
  has_many :recipes

  validates :name, presence: true
  validates :email, presence: true, allow_blank: false
  validates :encrypted_password, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  # GET /foods
  def index
    @foods = Food.where(user_id: current_user.id).order(created_at: :asc)
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  def shopping_list
    @foods = Food.where(user_id: current_user.id)
    @ingredients = RecipeFood.joins(:recipe).where(recipes: { user_id: current_user.id })
  end

  # POST foods/create
  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE foods/delete/:id
  def destroy
    @food = Food.find(params[:id])
    @food.destroy!
    redirect_to foods_path, notice: 'Food was successfully destroyed.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.new
    @foods = Food.order(created_at: :asc)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    if @recipe_food.save
      redirect_to recipes_path, notice: 'Ingredient is successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.destroy
      redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Ingredient is successfully deleted.'
    else
      redirect_to recipe_path(@recipe_food.recipe_id), alert: 'Failed to delete ingredient.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[show public_recipes]

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @food = Food.all
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
    @recipe_foods = RecipeFood.includes([:food]).all
  end

  def new
    @recipe = Recipe.new
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)

    redirect_to recipe_path(@recipe)
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cook_time, :description,
                                   :public).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with model: @food, url: create_food_path, local: :true do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    <%= form.label :name, class: "mb-2", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :measurement_unit, class: "mb-2", style: "display: block" %>
    <%= form.text_field :measurement_unit, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :quantity, class: "mb-2", style: "display: block" %>
    <%= form.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :price, class: "mb-2", style: "display: block" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :user_id, class: "mb-2", style: "display: block" %>
    <%= form.text_field :user_id, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= button_to "Create Food", create_food_path, method: :post, class: "btn btn-primary btn-block mb-3 w-10" %>
  </div>
<% end %>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-5 text-center">Foods</h1>
<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
    <div id="foods">
      <div class="d-flex justify-content-end">
        <%= link_to "Add food", add_food_path, class: "fs-6 btn btn-primary me-4 mb-4" %>
      </div>
      <table id='foods_table' class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Measurement unit</th>
            <th scope="col">Price</th>
            <th scope="col">Action</th>
          </tr>
        </thead>

        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.name%></td>
              <td><%= food.quantity%></td>
              <td><%= food.measurement_unit%></td>
              <td>$ <%= food.price%></td>
              <td><%= link_to "Delete", delete_food_path(food.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">New food</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">

    <%= render "form", food: @food %>
    <br>

    <div>
      <%= link_to "Back to foods", foods_path %>
    </div>
    
  </div>
</div>

app/views/foods/shopping_list.html.erb
<section>
  <% @food_table_data = [] %>
  <% @food_to_buy = 0 %>
  <% @total_food_value = 0 %>
  <% @foods.each do |food| %>
    <% @ingredient_quantity = @ingredients.where(food_id: food.id).sum(:quantity) %>
    <% if @ingredient_quantity >= food.quantity %>
      <% @quantity_diff = @ingredient_quantity - food.quantity %>
      <% @total_price = @quantity_diff * food.price %>
      <% @food_table_data.push([food.name, @quantity_diff, @total_price]) %>
      <% @food_to_buy += 1 %>
      <% @total_food_value += @total_price %>
    <% end %>
  <% end %>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
    <h1 class="mb-5 text-center">Shopping List</h1>
    <p class="mb-5 text-center"><span>Ammount of food items to buy <%=@food_to_buy%>.</span>  <span>Total value of food needed $<%=@total_food_value%></span></p>

    <table id='foods_table' class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        <%@food_table_data.each do |data|%>
          <tr>
            <td><%= data[0] %></td>
            <td><%= data[1] %></td>
            <td><%= data[2] %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto px-4">
      <li class="nav-item active">
        <%= link_to "Foods", root_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
         <%= link_to "Recipes", recipes_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
          <%= link_to "Shopping List", shopping_list_path, class:"navbar-brand fs-6" %>
      </li>
    </ul>
    </div>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "fs-6 btn btn-primary me-4" %>
</nav>

app/views/layouts/_navbar_login.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto px-4">
      <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class:"navbar-brand fs-6" %>
      </li>
    </ul>
    </div>
    <%= link_to 'Sign up', new_user_registration_path, class: "fs-6 btn btn-primary me-4" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render "layouts/navbar" %>
  <% else %>
  <%= render "layouts/navbar_login" %>
  <% end %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/index.html.erb
<h1>RecipeFoods#index</h1>
<p>Find me in app/views/recipe_foods/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">New Ingredient</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
    
    <%= form_with model: @recipe_food, url: create_recipe_food_path, local: :true do |form| %>
      <% if @recipe_food.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this Ingredient from being saved:</h2>
  
          <ul>
            <% @recipe_food.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      
    <%= form.hidden_field :recipe_id, value: @recipe.id%>
      <div class="field form-outline">
        <%= form.label :food_id, 'Select Food', class: "mb-2", style: "display: block" %>
        <%= form.select :food_id, options_for_select(@foods.pluck(:name, :id)), {}, { class: "form-control" } %>
      </div>

      <div class="form-outline mb-4">
        <%= form.label :quantity, class: "mb-2", style: "display: block" %>
        <%= form.number_field :quantity, class: "form-control" %>
      </div>
  
      <div class="form-outline mb-4">
        <%= form.submit "Create Ingredient", class: "btn btn-primary btn-block mb-3 w-10" %>
      </div>
    <% end %>
 
    <br>

    <div>
      <%= link_to "Back to recipe", recipes_path %>
    </div>

  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    <%= form.label :name, class: "mb-2", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :preparation_time, class: "mb-2", style: "display: block" %>
    <%= form.text_field :preparation_time, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :cook_time, class: "mb-2", style: "display: block" %>
    <%= form.text_field :cook_time, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :description, class: "mb-2", style: "display: block" %>
    <%= form.text_area :description, class: "form-control", style: "height: 10rem" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :public, class: "mb-2", style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class="form-outline mb-4">
    <%= form.submit class: "btn btn-primary btn-block mb-3 w-10" %>
  </div>

<% end %>

app/views/recipes/_public_btn.html.erb
<%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch) do |form| %>
    <%= form.submit(@recipe.public? ? 'Make Private' : 'Make Public', class: 'btn btn-primary') %>
<% end %>
  

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="d-flex justify-content-between">
    <%= content_tag :p, recipe.name, class: "fs-3" %>
    <%= render "recipes/public_btn" %>
  </div>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cook time:</strong>
    <%= recipe.cook_time %>
  </p>

  <p class="mb-3">
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/_recipes.html.erb
<table class="table table-borderless pt-3">
  <tbody class="border border-primary-subtle">
    <tr>
      <td><%= link_to recipe.name, recipe %></td>
      <td colspan="3"><%= recipe.description %></td>
    </tr>
    <tr>
    <td>
    </td>
    </tr>
    <tr>
      <td><%= button_to "Remove", recipe, method: :delete, class: "fs-6 btn btn-primary me-4 mb-4" %></td>
      </tr>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green" style="margin: 0 20%;"><%= notice %></p>
<p style="color: green"><%= notice %></p>

<h1 class="mb-5 text-center" style="margin-top: -2.5rem">Recipes</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
  
    <div class="d-flex justify-content-end">
      <%= link_to "Add new Recipe", new_recipe_path, class: "fs-6 btn btn-primary me-4 mb-4" %>
    </div>

    <div id="recipes">
      <% @recipes.each do |recipe| %>
        <%= render 'recipes', recipe: recipe %>
      <% end %>
    </div>

  </div>
</div>

app/views/recipes/new.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">New Recipe</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">

    <%= render "form", recipe: @recipe %>
    <br>

    <div>
      <%= link_to "Back to recipes", recipes_path %>
    </div>
    
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">Public Recipes</h1>

<div class="tab-content d-flex justify-content-center">
<div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
<table class="table table-borderless pt-3">
<% @recipes.each do |recipe| %>
  <% @ingredients = @recipe_foods.where(recipe_id: recipe.id) %>
  <% @total_price = 0 %>
  <% @ingredients.each do |item| %>
    <% @total_price += item.food.price * item.quantity %>
    <% end %>
    <tbody class="border border-primary-subtle">
    <tr>
      <td><%= link_to recipe.name, recipe %></td>
      <td><%= recipe.description %></span></td>
    </tr>

    <tr>
      <td><span> by <%= recipe.user.name %></span></td>
      <td>The total price is $<%= @total_price %></td>
    </tr>

    </tbody>
    <% end %>
</table>
  </div>
  </div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to recipes", recipes_path %>
<h1>Recipe</h1>

<h1 class="mb-5 text-center">Recipe Details</h1>
<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">

    <%= render @recipe %>
    <div class="d-flex justify-content-between">
      <%= link_to "Generate Shopping List", shopping_list_path, class: "btn btn-primary" %>
      <% if current_user == @recipe.user %>
        <%= link_to "Add Ingredients", add_recipe_food_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
    <hr>
    <div>

      <div id="recipes">
        <table id='foods_table' class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Quantity</th>
              <th scope="col">Value</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe_foods.each do |recipe_food| %>
              <% food_item = @food.find { |food| food.id == recipe_food.food_id } %>
              <tr>
                <td><%= food_item.name%></td>
                <td><%= recipe_food.quantity%></td>
                <td>$ <%= recipe_food.quantity * food_item.price %></td>
                <td><%= link_to "Delete", delete_recipe_food_path(recipe_food.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>